public class prctie {
    public static void nums(){
        Integer a = 30;
        Integer b = 40;
        Integer c= 50;
        Integer d = 60;
        
        if(b>c && b>c && b>d){
            System.debug('b is greater');
        }

        else if(a>b && a>c && a>d){
            System.debug ('a is greater');
        }
        
        else if(c>a && c>b && c>d){
            System.debug ('c is greater');
        }
        
        else{
            System.debug ('d is greater');
        }
    }
    public static void Naruto(){
        System.debug ('Konnichiwa Naruto Uzumaki');
    
    
Integer i = 0;
    for(i=20; i>1; i=i-5){
        System.debug(i);
    }
            List<Integer> nums = new List<Integer>{10,20,30,40,50,60};
        for (Integer num: nums){
            
            if(num>45){
                
               
                System.debug(num + ' is greater');}
                else{ 
					System.debug(num+ ' is smaller');
				}
            }
        }
	}